POST http://localhost:5000/api/supergeroes HTTP/1.1
Content-Type: application/json

# {
#   "nickName": "Superman",
#   "realName": "Clark Kent",
#   "originDescription": "He was born Kal-El on the planet Krypton, before being rocketed to Earth as an infant by his scientist father Jor-El, moments before Krypton's destruction",
#   "catchPhrase": "'Look, up in the sky, it's a bird, it's a plane, it's Superman!'",
#   "powerName":["impenetrability","superpower","flight","self-healing","supervision and super hearing"],
# "imagePath": ["test link","test link","test link"]
# }

{
  "nickName": "Spiderman",
  "realName": "Peter Parker",
  "originDescription": "Once he was an ordinary schoolboy, but he was bitten by a radioactive spider and endowed with wonderful abilities. Once he did not stop a petty robber when there was an opportunity and he killed his uncle, which injured the Spider and he decided to fight evil",
  "catchPhrase": "'The more strength, the more responsibility'",
"powerName":["superhuman reflexes","'Spider-instinct'","ability to adhere to hard surfaces","web production"],
  "imagePath": ["test link","test link","test link"]
}

# {
#   "nickName": "Batman",
#   "realName": "Bruce Wayne",
#   "originDescription": "His parents were killed in an alley by a petty robber, which inflicted severe mental trauma on the boy and he decided to fight evil",
#   "catchPhrase": "'Because I am Batman!'",
#   "powerName":["intelligence","extensive knowledge","martial arts knowledge","dexterity"],
# "imagePath": ["test link","test link","test link"]
# }

# {
#   "nickName": "Hulk",
#   "realName": "Bruce Banner",
#   "originDescription": "Scientist who has been exposed to gamma rays that release his inner demon Hulk during times of stress",
#   "catchPhrase": "'Hulk smash','Hulk breaking'",
#   "powerName":["superhuman strength and speed","endurance","flight"],
# "imagePath": ["test link","test link","test link"]
# }

# {
#   "nickName": "Iron Man",
#   "realName": "Tony Stark",
#   "originDescription": "A large capitalist and arms dealer, he once fell into the hands of terrorists where he almost died, but escaped by developing his wonderful suit. After that, he decided to fight evil",
#   "catchPhrase": "'I am iron man!'",
#   "powerName":["high level of intelligence","broad knowledge of science and technology","connection with the world wide web","armored suits"],
# "imagePath": ["test link","test link","test link"]
# }

# {
#   "nickName": "Flash",
#   "realName": "Barry Allen",
#   "originDescription": "His father was sent to prison for the murder of his mother, which he did not commit, and he is determined to prove his father's innocence. Somehow he was struck by lightning and endowed with the ability to quickly move in time and space",
#   "catchPhrase": "'Because I'm super fast!'",
#   "powerName":["able to move, think and react with superhuman speed","able to read and perceive information at super speed","much tougher than an ordinary person"],
# "imagePath": ["test link","test link","test link"]
# }