const ACTION_TYPES = {
  CREATE_SUPERHERO_REQUEST: "CREATE_SUPERHERO_REQUEST",
  CREATE_SUPERHERO_SUCCESS: "CREATE_SUPERHERO_SUCCESS",
  CREATE_SUPERHERO_ERROR: "CREATE_SUPERHERO_ERROR",

  UPDATE_SUPERHERO_REQUEST: "UPDATE_SUPERHERO_REQUEST",
  UPDATE_SUPERHERO_SUCCESS: "UPDATE_SUPERHERO_SUCCESS",
  UPDATE_SUPERHERO_ERROR: "UPDATE_SUPERHERO_ERROR",

  GET_SUPERHEROES_REQUEST: "GET_SUPERHEROES_REQUEST",
  GET_SUPERHEROES_SUCCESS: "GET_SUPERHEROES_SUCCESS",
  GET_SUPERHEROES_ERROR: "GET_SUPERHEROES_ERROR",

  DELETE_SUPERHERO_REQUEST: "DELETE_SUPERHERO_REQUEST",
  DELETE_SUPERHERO_SUCCESS: "DELETE_SUPERHERO_SUCCESS",
  DELETE_SUPERHERO_ERROR: "DELETE_SUPERHERO_ERROR",
};

export default ACTION_TYPES;
